server:
  port: 8090

mail:
  smtp:
    service: smtp.qq.com        #对应发送邮件的smtp服务器地址
    port: 587                   #对应发送邮件的smtp服务器端口
  from:
    address: 1612268911@qq.com  #发件人邮箱
    smtp:
      pwd: xcpudycewrsbdajj     #smtp授权码
    nicname: 呵呵               #收件显示姓名
