mybatis:
  type-aliases-package: com.cszt.domain
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:MybatisConfig.xml
spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081