#server:
#  port: 9003
### Dubbo 服务提供者配置
#spring:
#  application:
#    name: dubbo-provider
#  dubbo:
#    registry:
#      address: zookeeper://localhost:3181
#    protocal:
#      name: dubbo
#      port: 20880
#    scan: com.cszt.service
#
##spring.application.name=dubbo-provider
##spring.dubbo.registry.address=zookeeper://localhost:2181
##spring.dubbo.protocol.name=dubbo
##spring.dubbo.protocol.port=20882
##spring.dubbo.scan=com.xxx.school.service
##server.port=9003