server:
  port: 8765
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 100000
spring:
  application:
    name: EurekaServer
send:
  message: 【%s】欢迎你！

#安全认证
#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin