server:
  port: 8080
spring:
  application:
      name: demo
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456



logging:
  file: ${spring.application.name}
  path: /opt/logs/${spring.application.name}
  level:
    com:
      szzt:
        smart: debug
mybatis:
  mapper-locations: classpath*:com.cszt.mapper/*.xml
  type-aliases-package: com.szzt.smart.demo.entity

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址  （我配的是本地地址）
#spring.redis.host=127.0.0.1
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=123456
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=0










