mybatis:
  type-aliases-package: com.cszt.domain
spring:
  profiles:
    active: pro  #当前使用环境配置application-pro
  datasource:
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    pool:
      max-wait: 60000
      max-idle: 8
      max-active: 8
      min-idle: 0
    database: 0