server:
  port: 8081
mybatis:
  type-aliases-package: com.cszt.pojo
  mapper-locations: classpath*:*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver






