server:
  port: 8080

swagger:  #swagger配置
   enable: true  # 是否开启swagger，建议生产关闭，默认true
   basePackage: com.szzt.smart.NewTest.controller  #swagger扫描的api包，不能为空
   title:  接入API列表  # 标题
   description: 接入API列表 #描述
   groupName: group-1



spring:
  profiles:
      active: local
  application:
      name: NewTest


datasource:
        writeDS:
             url: jdbc:mysql://172.20.3.36:3306/test?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;noAccessToProcedureBodies=true&amp;generateSimpleParameterMetadata=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
             username: root
             password: 123456
             driverClassName: com.mysql.jdbc.Driver
        readDS:
             url: jdbc:mysql://172.20.3.36:3306/test?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;noAccessToProcedureBodies=true&amp;generateSimpleParameterMetadata=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
             username: root
             password: 123456
             driverClassName: com.mysql.jdbc.Driver

smartMybatis:
    aliasPackage: com.szzt.smart.NewTest.entity
    mapperLocation: classpath*:com.cszt.mapper/**/*.xml
    mapper-scanner: com.szzt.smart.NewTest.mapper
    idStrategy: AUTO



#logging:
#  file: ${spring.application.name}
#  path: /opt/logs/${spring.application.name}
#  level:
#    com:
#      szzt:
#        smart: debug
#apiDoc:
#  enable: true
#  title: 接口文档 # 标题
#  description: 接口文档描述
#  version: 1.0.0 #版本
#  packageName: com.szzt.smart.NewTest.controller #指定生成哪个包下controller的文档





